# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{powerleveling}
  s.version = "1.0.25"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Timo Rößner"]
  s.date = %q{2011-02-01}
  s.description = %q{A common library for everyting related to powerleveling.}
  s.email = %q{timo.roessner@googlemail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "powerleveling.gemspec",
    "lib/powerleveling/access_id.rb",
    "lib/powerleveling/api_key.rb",
    "lib/powerleveling/basic_event.rb",
    "lib/powerleveling/cassandra.rb",
    "lib/powerleveling/cassandra_helper.rb",
    "lib/powerleveling/dependencies.rb",
    "lib/powerleveling/event.rb",
    "lib/powerleveling/event_type.rb",
    "lib/powerleveling/messages.rb",
    "lib/powerleveling/redis.rb",
    "lib/powerleveling/verifier.rb",
    "spec/lib/api_key_spec.rb",
    "spec/lib/basic_event_spec.rb",
    "spec/lib/event_spec.rb",
    "spec/lib/event_type_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/troessner/powerleveling}
  s.licenses = ["TBA"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{nowarning}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A common library for everyting related to powerleveling.}
  s.test_files = [
    "spec/lib/access_id_spec.rb",
    "spec/lib/api_key_spec.rb",
    "spec/lib/basic_event_spec.rb",
    "spec/lib/event_spec.rb",
    "spec/lib/event_type_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activemodel>, ["= 3.0.3"])
      s.add_runtime_dependency(%q<cassandra>, ["= 0.9.0"])
      s.add_runtime_dependency(%q<factory_girl>, ["= 1.3.3"])
      s.add_runtime_dependency(%q<jeweler>, ["= 1.5.1"])
      s.add_runtime_dependency(%q<random_data>, ["= 1.5.2"])
      s.add_runtime_dependency(%q<redis>, ["= 2.0.1"])
      s.add_runtime_dependency(%q<yajl-ruby>, ["= 0.7.8"])
      s.add_runtime_dependency(%q<activemodel>, ["= 3.0.3"])
      s.add_runtime_dependency(%q<cassandra>, ["= 0.9.0"])
      s.add_runtime_dependency(%q<redis>, ["= 2.0.1"])
      s.add_runtime_dependency(%q<yajl-ruby>, ["= 0.7.8"])
    else
      s.add_dependency(%q<activemodel>, ["= 3.0.3"])
      s.add_dependency(%q<cassandra>, ["= 0.9.0"])
      s.add_dependency(%q<factory_girl>, ["= 1.3.3"])
      s.add_dependency(%q<jeweler>, ["= 1.5.1"])
      s.add_dependency(%q<random_data>, ["= 1.5.2"])
      s.add_dependency(%q<redis>, ["= 2.0.1"])
      s.add_dependency(%q<yajl-ruby>, ["= 0.7.8"])
      s.add_dependency(%q<activemodel>, ["= 3.0.3"])
      s.add_dependency(%q<cassandra>, ["= 0.9.0"])
      s.add_dependency(%q<redis>, ["= 2.0.1"])
      s.add_dependency(%q<yajl-ruby>, ["= 0.7.8"])
    end
  else
    s.add_dependency(%q<activemodel>, ["= 3.0.3"])
    s.add_dependency(%q<cassandra>, ["= 0.9.0"])
    s.add_dependency(%q<factory_girl>, ["= 1.3.3"])
    s.add_dependency(%q<jeweler>, ["= 1.5.1"])
    s.add_dependency(%q<random_data>, ["= 1.5.2"])
    s.add_dependency(%q<redis>, ["= 2.0.1"])
    s.add_dependency(%q<yajl-ruby>, ["= 0.7.8"])
    s.add_dependency(%q<activemodel>, ["= 3.0.3"])
    s.add_dependency(%q<cassandra>, ["= 0.9.0"])
    s.add_dependency(%q<redis>, ["= 2.0.1"])
    s.add_dependency(%q<yajl-ruby>, ["= 0.7.8"])
  end
end

